# Generated by Django 5.2 on 2025-04-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('detalhes', models.TextField()),
                ('image', models.ImageField(upload_to='fotos/')),
            ],
        ),
    ]
