# Generated by Django 5.2 on 2025-04-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='name',
        ),
    ]
